name: repo__auto-update-param-branch

on:
  push:
    branches:
      - main # Trigger on pushes to main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Merge develop -> test-space/pk
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout develop
          git rebase origin/develop
          git push --force-with-lease origin develop
