name: repo__manual-reset-param-branch

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Reset test-space/pk to develop
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout test-space/pk
          git reset --hard origin/develop
          git push --force-with-lease origin test-space/pk
